Full draft  of user example complete
UBC-MDS/strapvizpy pull request #36
Opened 2022-01-27 15:06 UTC by voremargot

This is the first draft of the package examples for the documentation! Please take a look. 

@zackt113 I was going to put an example of how you can save your plots to your computer but I realized your function doesn't output the plot object, it only renders it! I am not sure if this is something we can easily change (ultimately it would be great if you could easily save your plots).

2022-01-27 19:00 UTC, gauthampughazhendhi commented on docs/example.ipynb
> +    "<center> <h1> How to use strapPy</h1> </center>\n",
```suggestion
    "<center> <h1> How to use StrapPy</h1> </center>\n",
```

@voremargot just a small name change

2022-01-27 19:00 UTC, gauthampughazhendhi requested changes
@voremargot this looks great! thanks for the good work. I have only one change

2022-01-27 21:15 UTC, BooleanJulien approved these changes
lgtm!

2022-01-27 21:16 UTC, zackt113 approved these changes
Everything looks good!

2022-01-28 03:24 UTC, voremargot commented
Updates have been made! I will merge!

2022-01-28 03:24 UTC, merged